### ISSUE TITLE
OpenJO - EAX Effects Not Working

### ISSUE THREAD

**Issue by marigi64** [JACoders/OpenJK#1158]
EAX effects like reverb and occlusion don't occur when EAX is enabled (Only for OpenJO).
I'm using DSOAL to test for both OpenJO and the original game (I made sure I'm running the 32-bit version of OpenJO).

The Effect is Quite apparent on "yavin_temple" in the original game:

https://github.com/JACoders/OpenJK/assets/53112738/f5200933-ebef-4786-8cea-d118ebae6c95

**Comment by MoritzJT** [comment]
Where did you get your DSOAL binaries?

**Comment by marigi64** [comment]
https://github.com/ThreeDeeJay/dsoal/releases/tag/latest (I use the 32-bit binary)

**Comment by marigi64** [comment]
I made a mistake on my end (my openal32.dll was wrong). Sorry about this.

**Comment by anohren** [comment]
> (I made sure I'm running the 32-bit version of OpenJO)

What's the reason this was mentioned? Is EAX or OpenAL Soft expected to not work on the 64-bit version? 

I can't figure out what the game wants for EAX to be enabled. Not even sure which sound api is being used or when...

**Comment by taysta** [comment]
> > (I made sure I'm running the 32-bit version of OpenJO)
> 
> What's the reason this was mentioned? Is EAX or OpenAL Soft expected to not work on the 64-bit version? 
> 
> I can't figure out what the game wants for EAX to be enabled. Not even sure which sound api is being used or when...

Correct, the EaxMan DLL required for EAX to work in this game only exists in 32-bit, and is not compatible to 64-bit engine builds.

**Comment by anohren** [comment]
🤦‍♂️ That explains it, thanks! There's a few hours of troubleshooting and experimenting down the drain. OpenAL Soft works now (although I don't see the point of using DSOAL in particular — isn't that redundant?)

I haven't used OpenJK before and just assumed since the 64 bit exe was next to the 32 bit one in the releases, that the two would be functionally equivalent. That they both came with the same set of DLLs, including EaxMan, didn't help my understanding even after reading some of the existing EAX issues here. 

Dis I miss the mention of these differences somewhere? 

Honestly I didn't even know what the "OpenJO" files were in the releases so I might have missed the mention of that as well — I just assumed it was for Outcast, but it felt a bit wrong when the OpenJK readme said that Outcast is supported by "OpenJK", and that that was the literal name of the other file. Much first time confusion for me.

**Comment by ensiform** [comment]
The releases are just re-pulling the same 32 bit dlls shipped from the original game. Packaging is broken then but they are 100% not compatible with 64-bit engine. It is proprietary code that hasn't been released to public for 64-bit support.

**Comment by Archangel35757** [comment]
> The releases are just re-pulling the same 32 bit dlls shipped from the original game. Packaging is broken then but they are 100% not compatible with 64-bit engine. It is proprietary code that hasn't been released to public for 64-bit support.

A 64-bit version of EAXMAN.dll is in alpha testing.  I just need time to get with @taysta and finalize things.  I also need some free time-- which I have very little of lately.

**Comment by anohren** [comment]
Just shared my first time experience in case you wanted to add something to the documentation. Or I could add some details to the readme if you'd like.

**Comment by ensiform** [comment]
> > The releases are just re-pulling the same 32 bit dlls shipped from the original game. Packaging is broken then but they are 100% not compatible with 64-bit engine. It is proprietary code that hasn't been released to public for 64-bit support.
> 
> A 64-bit version of EAXMAN.dll is in alpha testing.  I just need time to get with @taysta and finalize things.  I also need some free time-- which I have very little of lately.

Which one is this? Rewritten without proprietary or what? If it's still some magical proprietary version we don't really want it as it's not really compatible
