### ISSUE TITLE
Changing Video Settings Causes Repeating Initialization...

### ISSUE THREAD

**Issue by aFoxNamedMorris** [JACoders/OpenJK#433]
Heya. I compiled the 64-Bit version of OpenJK. I installed all the needed assets, started it up, and everything seemed fine, at least until I tried to change the video settings. Whether I edit the cfg file or use the in-game UI, the game begins to Initialize over and over again as if just starting the game. No errors in the output, no suspicious messages. I am using a stock Lenovo Ideapad, running 64-bit Ubuntu Linux.

**Comment by xycaleth** [comment]
I'm in the process of removing this for unified SDL. I don't see it being all that important and we can try to add it back in at some later date if we really want it...

**Comment by HEXcube** [comment]
The latest 2015-02-10 build from [Official OpenJK builds](http://builds.openjk.org/) seems to have solved this bug. The new build works fine on *Ubuntu 14.04LTS* _"Trusty Tahr"_ without needing `seta r_restartOnResize "1"` option. Older builds when run on Ubuntu 14.04LTS had this restart loop problem on startup, though they ran fine on Ubuntu 12.04LTS.

**Comment by xycaleth** [comment]
The cvar was removed which is why it works now! :p but thank you for noticing

**Comment by HEXcube** [comment]
@xycaleth But, do you know why it ran fine in *Ubuntu 12.04LTS* even before the cvar was removed?

**Comment by xycaleth** [comment]
Unfortunately not. I didn't have any intention of fixing it properly so I didn't look into it. If I were to guess, I would say that something in the window manager between 12.04 and 14.04 changed, perhaps due to a window sizing event being sent at start up by the WM in 14.04, and not in 12.04, which would cause the 'resize' code to be triggered again, and thus the window to repeatedly restart.
