### ISSUE TITLE
Radar draw order

### ISSUE THREAD

**Issue by ghost** [JACoders/OpenJK#517]
In non-siege gametypes the radar is drawn on-top of the objects which makes it hard to see

Siege: 
![siege](https://f.cloud.github.com/assets/1158472/2471780/8c09ee1a-b02b-11e3-8e1c-72b164c3d85b.jpg)
TFFA: 
![tffa](https://f.cloud.github.com/assets/1158472/2471782/9b8d9ee0-b02b-11e3-8e47-85d92761b802.jpg)

**Comment by xycaleth** [comment]
The problem can be reproduced using base assets, but the effect is more subtle. I think I have a PK3 in my base folder which is messing up the shaders, but same point applies:

TFFA
![TFFA](https://dl.dropboxusercontent.com/u/874909/jka/shot2015-01-26_18-56-22.jpg)

Siege
![Siege](https://dl.dropboxusercontent.com/u/874909/jka/shot2015-01-26_18-59-53.jpg)

**Comment by xycaleth** [comment]
The issue is in the `RB_RotatePic` and `RB_RotatePic2` functions. These bypass the tesselator so rotated images might actually get drawn before textures drawn using `RB_StretchPic` which does use the tesselator. Consider this situation:

In cgame:
1. Draw radar background texture without rotation (uses `CG_DrawPic`)
2. Draw player icon with rotation (uses `CG_DrawRotatePic2`)

At draw time:
1. Radar background gets added to the tesselator to be drawn when shader changes
2. Rotated player icon is drawn *straight away*.
3. A bit later on, something wants to add to the tesselator with a different shader. Radar background gets drawn at this point.

The problem only happens in non-siege game types because these do not usually call any `CG_DrawPic` functions after drawing the radar background - they're used for map items usually which don't show up in non-siege game types.

When `CG_DrawPic` *does* get called after drawing the radar background, this means that steps 2 and 3 in my above example (at draw time) are switched, so the background is drawn before the player icon.

**Comment by xycaleth** [comment]
I can fix the `RB_RotatePic*` functions to make use of the tessellator, but this then breaks other things like the rocket lock. It seems this relied on old GL state to make it transparent, and now by adding it to the tessellator, the GL state is set up correctly for the shader it uses, and it looks wrong :/ This is the same problem we had in #584.

**Comment by ensiform** [comment]
Yeah but do you want to not use the tessellator for Rend2?  Because this would need to be fixed there too eventually.

**Comment by xycaleth** [comment]
So shall we fix this and break rocket lock rendering?

**Comment by ensiform** [comment]
Is rocket lock all that uses the broken rotatepic ?

**Comment by xycaleth** [comment]
Looks like it's only rocket lock, radar and disruptor zoom (the ticks to show you how much ammo you have left when zoomed in) use the `RotatePic` functions. I guess I'll just add a hack in to fix rocket lock images...
