### ISSUE TITLE
Display refresh works only after minimize once

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#652]
Latest build version from 03-31-2015, Windows 7, MP. I have desktop resolution of 1920x1080@60hz and ingame videomode of 1024x768@75hz because it is the optimal mode to get 75hz on my screen. I have r_displayrefresh set on 75. When I run the game it start with 60hz, it is very notisable by vision, and only when I minimize (through "minimize command") and maximize the game it turns to 75hz. It's not seems like a big problem (for me, because I know how to fix it in few seconds), but people may not know how to activate 75hz.

**Comment by ensiform** [comment]
This isn't something controlled by OpenJK to my knowledge. SDL handles all window and display driver calls at that level.  Sounds like a bug between SDL and the video driver.

**Comment by xycaleth** [comment]
@sudge, do you play in fullscreen mode? `r_displayRefresh` only affects fullscreen mode.

Windowed applications are always refreshed at the same rate as your desktop because the image produced by the window is composited with the rest of the screen. The composited image is then displayed at the same time as everything else on the desktop.

If you run in fullscreen, then the application can "take ownership" of the display and refresh at a different rate from the desktop (as the desktop is no longer being rendered).

**Comment by sudge** [comment]
Of course in fullscreen mode. It happent like: I run the game, it starts with 1024x768@60hz, when I minimize, it is going to the desktop and 1920x1080@60hz mode, and when I maximize it back, it turns to 1024x768@75hz. If it cannot be strongly fixed, let it be like a known issue if someone looking for the solution in this case.

**Comment by Razish** [comment]
I have a 120hz/144hz monitor, I can run some tests later.

How are you verifying that the refresh rate is changing?
Is v-sync (r_swapInterval) turned on? Are you using non-default driver settings?
What is `com_maxFPS` set to?
At what point are you setting `r_swapInterval`, `com_maxFPS` and `r_displayRefresh`? Does the issue persist if you set them via command-line arguments?

**Comment by sudge** [comment]
It is quite easy to notice just by eyes that refresh rate changing, and yes, v-sync says 60fps at 1st and 75 fps at 2nd. Maxfps doesnt matter, 125-142-250 changes nothing. 

>At what point are you setting r_swapInterval, com_maxFPS and r_displayRefresh?

0; 125; 75

>Does the issue persist if you set them via command-line arguments?

What do you mean? Maxfps can only be set by command-line. I dont know if it can be set in *.bat file or not. I never rly use menu settings, cause it's much easier to use config file.

**Comment by Razish** [comment]
By command-line, I mean using a shortcut or batch (.bat) file as such: `openjk.x86.exe +set r_displayRefresh 75`

I assume you're only using config files to change these values? That may explain the issue at hand, which is why I suggested setting it via command-line.
My guess is, the value of r_displayRefresh is only read once when creating the window and display context (i.e. at startup, before the config file is read) and any subsequent changes are not causing the window/display context to be re-created with the new refresh rate (until you toggle fullscreen or otherwise cause a `vid_restart`)

**Comment by sudge** [comment]
>using a shortcut or batch (.bat) file as such: openjk.x86.exe +set r_displayRefresh 75

Doesnt works, still 60 at start and 75 after min-maximize.

**Comment by sudge** [comment]
fixed in new builds
