### ISSUE TITLE
Disable texture compression when using Intel driver on Linux

### ISSUE THREAD

**Issue by xycaleth** [JACoders/OpenJK#663]
People seem to be having issues with textures when texture compression is enabled. It would probably be a good idea to disable texture compression completely when running on Linux and using Intel's Mesa driver.

**Comment by ensiform** [comment]
Which string should be looked at ?

**Comment by smcv** [comment]
I haven't noticed any problems, and according to gfxinfo I have compressed textures enabled, but perhaps that's because I have `libtxc-dxtn-s2tc0` (a patent-avoiding version of S3TC) installed?

**Comment by smcv** [comment]
Checking this, I see the same quality loss as in #442 in the SP character creation screen, with `libtxc-dxtn-s2tc0` installed. I don't see it without that library; perhaps Mesa is transparently falling back to uncompressed textures when that library is missing?

"S2TC" is a cut-down version of S3TC specifically designed to avoid the patented bits, which is probably why it's lower-quality. https://wiki.freedesktop.org/dri/S3TC/ points to an implementation of actual S3TC, but none of the Linux distributions are likely to ship that any time soon, because they'd like to be distributable in the USA. Software patents, aren't they great.

A `GL_RENDERER` starting with `Mesa` is probably the best discriminator for "is this Mesa-based?". On two laptops with Mesa drivers for different graphics cards, I get:

* `GL_RENDERER: Mesa DRI R200 (RV250 4C66)  DRI2` - an old Radeon
* `GL_RENDERER: Mesa DRI Intel(R) Sandybridge Mobile` - modern Intel integrated graphics

The other major Mesa driver is nouveau for nVidia cards, for which you might want to match a renderer starting with Gallium, e.g. `GL_RENDERER: Gallium 0.4 on NVA8` is mentioned in http://comments.gmane.org/gmane.comp.web.opera.linux/7890
