### ISSUE TITLE
buildbot and pull requests

### ISSUE THREAD

**Issue by deepy** [JACoders/OpenJK#700]
https://github.com/graydon/bors/issues might be able to handle this in a satisfactory way.

**Comment by smcv** [comment]
See also #692, which uses Travis-CI rather than a buildbot, and doesn't do OS X, but should make it really easy to get PRs test-built for Linux and WIndows. Also, sysadmin tasks for the servers where it happens are someone else's problem :-)

(Feel free to send a PR for some random change to `smcv/OpenJK` to try it out - I've hooked that clone up to Travis-CI, <https://travis-ci.org/smcv/OpenJK>.)

**Comment by xycaleth** [comment]
With our current build system in place, we felt it was better to some how leverage this for pull requests as well. I had a look into it, and this is possible, but we had concerns about rogue pull requests which could potentially do an `rm -rf /` for example.

**Comment by smcv** [comment]
I agree that it would be bad to execute arbitrary code unreviewed, which means the build for an unreviewed PR has to be done in a container or virtual machine of some sort. Also, you probably want to do each build in a clean environment so it can't be polluted by changes made by previous builds, and so on. These are problems that can be solved to some extent, but they are also problems that other people with more time and more economies of scale are already working on :-)

That's one of the reasons I suggested Travis-CI - its build environment is an ancient version of Ubuntu, which caused me some headaches, but at least it's a standard of a sort. The "clean environment" and "sandboxing" aspects are already there, and anyone who wants to do so can easily hook up their clone of OpenJK to an identical build environment.

On that note, it was entirely deliberate that I put as much as possible of the build setup into the PR rather than in my own Travis-CI configuration, so that anyone who clones the repo can see it, and there's as little "secret sauce" as possible. If the authors of your buildbot glue (I assume there must be some script analogous to my `tools/travis-build.sh`) are willing to license it like OpenJK and commit it to this repository, then that would make it easier for contributors without access to your buildslaves to understand how the official builds work, and potentially even fix build issues?

**Comment by deepy** [comment]
Buildbots output contains the entire process, all from secret sauce to environment variables. 

Travis doesn't do windows or osx out of the box, the osx support is experimental. 
And beyond that there's more to the builds, there's the publishing too. 

If travis could handle all that then that'd be great, but as of now it's still lacking and thus we can't really switch to travis. We'd still have to maintain the current system. 

Moving the build commands out of buildbot and into the repo is probably a good idea though , someone should investigate that. I'm swamped at the moment so make a separate issue for that and work on it there and I'll update buildbot when it's done :-)

**Comment by smcv** [comment]
> We'd still have to maintain the current system.

Yeah, not disagreeing with that for the "official snapshot" builds. All I'm saying is that the best answer for smoke-testing git master and PRs is not necessarily the same as the best answer for publishing official snapshots.

**Comment by deepy** [comment]
While travis is (currently) superior to buildbot when it comes to testing PRs, it is awfully far behind when it comes to testing master, we currently have windows, linux and OS X being built instantly whenever the code changes, travis offers the same but only with full support for Linux. That's 1/3 and really a disappointment.

And for the future, if that raspberry pi work ever gets anywhere we could test builds there through buildbot too, but not through travis.

This issue is about seeing if buildbot can handle PR testing.

We really should start another issue for coordinating build scripts (since there's no point in maintaining two separate ones when at least the linux one is likely to be identical)

**Comment by deepy** [comment]
https://github.com/barosl/homu is the newer version of bors

**Comment by deepy** [comment]
homu does it by merging it into a separate branch (try by default) and having specific buildbots try it.
It then reports back in the issue.

Though the workflow for homu seems somewhat different to ours.
