### ISSUE TITLE
Porting to OpenBSD ok?

### ISSUE THREAD

**Issue by rfht** [JACoders/OpenJK#948]
I got the most recent commit to build and run on OpenBSD. Would like to prepare a package. Any objections?

In addition, OpenBSD encourages fixing unsafe operations, like strcat/strcpy -> strlcat/strlcpy. I patched a ton of those (a few broke the game and I removed them again). Since I'm working on OpenBSD, I'm used to having strlcat/strlcpy in system libs, but AFAIK that's not the case on most Linux. Any preference regarding how to best integrate that into upstream? #ifdefs, cmake magic ... ?

**Comment by Razish** [comment]
I would like to see *BSD support but kept unobtrusive.

**Comment by kaashif** [comment]
With #941, OpenJK builds and runs very well on OpenBSD/amd64, as far as I can tell. I've played a few games in multiplayer and it seems to work. I don't think you have to worry about OpenBSD support being obtrusive, it already works almost unmodified.

**Comment by thfrwn** [comment]
My attempt to patch the strcat/strcpy collapsed since after spending 2 weeks of removing obvious breakage, I'm now faced with the fact that there is a number of more subtle bugs that have been introduced by my efforts. At this point this isn't really worth the effort, especially for a 1-man team. 
So this will then remain unobtrusive at this point. Looks like OpenBSD would be the first *BSD then, if we get the port ready soon.

**Comment by xycaleth** [comment]
Looks like #941 got merged 😄 I can't vouch for how well the port works but hopefully people would report issues if they saw any by now.
